name: Install Conan
description: Install Conan
inputs:
  path:
    description: Conan installation path
    required: true
    default: ~/conan
outputs:
  conan:
    description: Path to the conan binary
    value: ${{steps.set-conan-path.outputs.path}}
runs:
  using: composite
  steps:
    - name: Create Python virtual environment
      shell: bash
      run: |
        python3 -m venv "${{input.path}}"
    - name: Install Conan
      shell: bash
      run: |
        "${{input.path}}/bin/pip" install --no-cache-dir conan
    - id: set-conan-path
      shell: bash
      run: |
        printf "::set-output name=conan::%s\n" "${{input.path}}/bin/conan"
